apiVersion: v1
kind: Service
metadata:
  name: codeplex-ai
  namespace: codeplex-ai
  labels:
    app.kubernetes.io/name: codeplex-ai
    app.kubernetes.io/component: api
    app.kubernetes.io/part-of: codeplex-ai
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: codeplex-ai
    app.kubernetes.io/component: api
